### ISSUE TITLE
create semver compatible tag for 0.2.0

### ISSUE THREAD

**Issue by UiP9AV6Y** [wolfmetr/ristretto-prometheus#4]
the release of [v0.2](https://github.com/wolfmetr/ristretto-prometheus/releases/tag/v0.2) does not follow the semver specification for version numbers. golang relies on this [numbering scheme](https://go.dev/doc/modules/version-numbers) for proper dependency tracking.

forcing golang to use the latest version results in the library being tracked as [v0.1.2-0.20240317204844-4cb344bd91cc](https://deps.dev/go/github.com%2Fwolfmetr%2Fristretto-prometheus/v0.1.2-0.20240317204844-4cb344bd91cc)

IMO there is no need for a new release; simply tagging 4cb344bd91ccd754de7851142c0b3b2939cbd860 again as v0.2.0 should suffice

**Comment by wolfmetr** [comment]
Thank you! I've published [v0.2.0](https://github.com/wolfmetr/ristretto-prometheus/releases/tag/v0.2.0)
