### ISSUE TITLE
Move built-in metrics descriptions to global variables

### ISSUE THREAD

**Issue by sashayakovtseva** [wolfmetr/ristretto-prometheus#9]
As a developer, I want to reuse same metric names in order to build grafana library panels across my app(s). I also want to distinguish my caches by name, which can be achieved by my custom const label.

To achieve this now I need to:
1) define `Desc` for each metric desired
2) register `Desc` once on app startup
3) use `WithMetric` with my defined `Desc`

I want to reuse `Desc` described in this package, so I don't have to write my own pkg or copy them across my apps.

**Comment by wolfmetr** [comment]
Thank you for your suggestion!

Would using `WithHitsCounterMetric()` (see [code reference](https://github.com/wolfmetr/ristretto-prometheus/blob/a00ca3ebda362c36de94e8618a782ea2563a97a8/options.go#L55)) and other predefined metrics, in combination with `WithConstLabels`, work for your use case?

If not, could you please clarify your request further or provide a draft example of the usage you’d like to see? This would help us better understand the issue.

Looking forward to your feedback!

**Comment by sashayakovtseva** [comment]
@wolfmetr turns out this package works as I expected already (same metrics with different const labels will successfully be registered with `prometheus.MustRegister`), sorry for raising this issue.

Here's an example of what I was looking for: https://github.com/sashayakovtseva/ristretto-prometheus/blob/reuse-desc/examples_test.go#L94

Do you want me to submit a PR with this example to this repo?

**Comment by sashayakovtseva** [comment]
closing this issue since everything already works as I expected. please let me know if you want me to create a PR with the example above
